export const PAGES = {
    LOGIN: '/login',
    HOME: '/',
    BANNERS: '/banners',
    BANNERS_CREATE: '/banners/create',
    BANNERS_DETAIL: '/banners/update',
    BANNERS_UPDATE: '/banners/update/:id',
    SERVICES: '/services',
    SERVICES_CREATE: '/service',
    SERVICES_DETAIL: '/service/:id',
    SOLUTIONS: '/solutions',
    SOLUTIONS_CREATE: '/solution',
    SOLUTIONS_DETAIL: '/solution/:id',
    NEWS: '/news',
    NEWS_CREATE: '/news/create',
    NEWS_DETAIL: '/news/update',
    NEWS_UPDATE: '/news/update/:id',
    REVIEWS: '/reviews',
    REVIEWS_CREATE: '/review',
    REVIEWS_DETAIL: '/review/:id',
    CERTIFICATES: '/certificates',
    CERTIFICATES_CREATE: '/certificate',
    CERTIFICATES_DETAIL: '/certificate/:id',
    NOT_FOUND_404: '/:pathMatch(.*)*',
}
