export const PAGES = Object.freeze({
    LOGIN: '/login',
    HOME: '/',
    BANNERS: '/banners',
    BANNERS_CREATE: '/banner',
    BANNERS_DETAIL: '/banner/:id',
    SERVICES: '/services',
    SERVICES_CREATE: '/service',
    SERVICES_DETAIL: '/service/:id',
    SOLUTIONS: '/solutions',
    SOLUTIONS_CREATE: '/solution',
    SOLUTIONS_DETAIL: '/solution/:id',
    NEWS: '/news',
    NEWS_CREATE: '/news_item',
    NEWS_DETAIL: '/news_item/:id',
    REVIEWS: '/reviews',
    REVIEWS_CREATE: '/review',
    REVIEWS_DETAIL: '/review/:id',
    CERTIFICATES: '/certificates',
    CERTIFICATES_CREATE: '/certificate',
    CERTIFICATES_DETAIL: '/certificate/:id',
    NOT_FOUND_404: '/:pathMatch(.*)*',
})
