export const PAGES = {
    LOGIN: '/login',
    HOME: '/',
    BANNERS: '/banners',
    BANNERS_CREATE: '/banners/create',
    BANNERS_DETAIL: '/banners/update',
    BANNERS_UPDATE: '/banners/update/:id',
    SERVICES: '/services',
    SERVICES_CREATE: '/services/create',
    SERVICES_DETAIL: '/services/update',
    SERVICES_UPDATE: '/services/update/:id',
    SOLUTIONS: '/solutions',
    SOLUTIONS_CREATE: '/solution',
    SOLUTIONS_DETAIL: '/solution/:id',
    NEWS: '/news',
    NEWS_CREATE: '/news/create',
    NEWS_DETAIL: '/news/update',
    NEWS_UPDATE: '/news/update/:id',
    REVIEWS: '/reviews',
    REVIEWS_CREATE: '/reviews/create',
    REVIEWS_DETAIL: '/reviews/update',
    REVIEWS_UPDATE: '/reviews/update/:id',
    CERTIFICATES: '/certificates',
    CERTIFICATES_CREATE: '/certificates/create',
    CERTIFICATES_DETAIL: '/certificates/update',
    CERTIFICATES_UPDATE: '/certificates/update/:id',
    NOT_FOUND_404: '/:pathMatch(.*)*',
}
